#!/usr/bin/env python

import urllib2
import time
import csv

#Request user data. Input from user will be placed into variables

choice = raw_input(
("For three individual axes values (X,Y,Z) enter A\n"
"For X-axis values enter X\n"
"For Y-axis values enter Y\n"
"For Z-axis values enter Z\n")
)
wait = raw_input("Do you want a delay before sampling begins Y or N\n")
if wait == 'Y':
    pause = input("How many minutes to delay?\n")
samples = input("How many samples (one minute each)?\n")
if wait == 'Y':
    print ('waiting...')
    for i in range(0, pause):
        delay = urllib2.urlopen("http://192.168.1.1/D")
        count = delay.read()
        print ('minute ' + str(i+1))
        delay.close()
print ('sampling...')        
for j in range(0, samples):
    W = 0                   #determines if the data will be written to file
    if choice == 'A':
        name = choice + ' ' + str(j) # file name is the type of data and loop number
        print (name)        #debugging step. displays name of file to be created
        mkr = urllib2.urlopen("http://192.168.1.1/A")
        accl = mkr.read()
        mkr.close()
        W = 1               #data was recieved so a write will be performed
    elif choice == 'X':
        name = choice + ' ' + str(j) # file name is the type of data and loop number
        print (name)
        mkr = urllib2.urlopen("http://192.168.1.1/X")
        accl = mkr.read()
        mkr.close()
        W = 1
    elif choice == 'Y':
        name = choice + ' ' + str(j) # file name is the type of data and loop number
        print (name)
        mkr = urllib2.urlopen("http://192.168.1.1/Y")
        accl = mkr.read()
        mkr.close()
        W = 1
    elif choice == 'Z':
        name = choice + ' ' + str(j) # file name is the type of data and loop number
        print (name)
        mkr = urllib2.urlopen("http://192.168.1.1/Z")
        accl = mkr.read()
        mkr.close()
        W = 1
        
    #if user made a valid choice data will be written to text file    

    if W == 1:
        f = open(name + '.txt',"w")
        f.write(accl)
        f.close

#if invalid choice was entered user is notified
        
if W == 0:
    print ("invalid entry")

print ("done reading")          #file has been written




